<?php
/**
 * Created by PhpStorm.
 * User: Дмитрий
 * Date: 03.08.2018
 * Time: 22:13
 */

class DK_Crud_Block_Adminhtml_Articles_Grid extends Mage_Adminhtml_Block_Widget_Grid
{

    public function __construct()
    {
        parent::__construct();
        $this->setDefaultSort('article_id');
        $this->setId('dk_crud_articles_grid');
        $this->setDefaultDir('asc');
        $this->setSaveParametersInSession(true);
    }

    protected function _getCollectionClass() {
        return 'dk_crud/articles_collection';
    }

    protected function _prepareCollection()
    {
        $collection = Mage::getResourceModel($this->_getCollectionClass());
        $this->setCollection($collection);
        return parent::_prepareColumns(); // TODO: Change the autogenerated stub
    }

    protected function _prepareColumns()
    {
        $this->addColumn('article_id',
            [
                'header'=> $this->__('ID'),
                'align' =>'center',
                'index' => 'article_id',
                'type' => 'checkbox'
            ]
        );

        $this->addColumn('title',
            [
                'header'=> $this->__('Title'),
                'index' => 'title'
            ]
        );
        $this->addColumn('description',
            [
                'header'=> $this->__('Description'),
                'index' => 'description'
            ]
        );
        return parent::_prepareColumns();
    }

    public function getRowUrl($row) {
        return $this->getUrl('*/*/edit', ['id' => $row->getId()]);
    }
}