<?php

class DK_Crud_Block_Adminhtml_Articles_Edit_Form extends Mage_Adminhtml_Block_Widget_Form
{

    public function __construct()
    {
        parent::__construct();
        $this->setId('dk_crud_articles_form');
        $this->setTitle($this->__('Article information'));
    }

    protected function _prepareForm()
    {
        $model = Mage::registry('dk_crud');
        $form = new Varien_Data_Form([
            'id' => 'edit_form',
            'action' => $this->getUrl('*/*/save', ['id' => $this->getRequest()->getParam('id')]),
            'method' => 'post'
        ]);
        $fieldset = $form->addFieldset('base_fieldset', [
            'legend'    => Mage::helper('checkout')->__('Article Information'),
            'class'     => 'fieldset-wide',
            ]
        );
        if ($model->getId()) {
            $fieldset->addField('article_id','hidden',[
                'name' => 'article_id'
            ]);
        }
        $fieldset->addField('title','text',[
            'name' => 'title',
            'label' => Mage::helper('checkout')->__('Title'),
            'title' => Mage::helper('checkout')->__('Title'),
            'required' => true,
        ]);
        $fieldset->addField('description','text',[
            'name' => 'description',
            'label' => Mage::helper('checkout')->__('Description'),
            'title' => Mage::helper('checkout')->__('Description'),
            'required' => true,
        ]);
        $fieldset->addField('status','select',[
            'name' => 'status',
            'label' => Mage::helper('checkout')->__('Status'),
            'title' => Mage::helper('checkout')->__('Status'),
            'value' => $model->getStatus(),
            'options' => ['1' => 'Enable', '0' => 'Disable']
        ]);

        $form->setValues($model->getData());
        $form->setUseContainer(true);
        $this->setForm($form);


        return parent::_prepareForm(); // TODO: Change the autogenerated stub
    }
}